### ISSUE TITLE
[Feature Request] View current transaction state

### ISSUE THREAD

**Issue by zbs** [cvmfs/cvmfs#2617]
It would be helpful for coordination between multiple admins to know if a transaction is currently underway before starting one. Something along the lines of `cvmfs_server check-transaction-status <repository-name>`
My current workaround is to start a transaction and see if it fails.

**Comment by siscia** [comment]
A similar answer.

I don't believe we are considering right now adding this feature, but there should be a transaction lock file in the filesystem when a transaction is open.

An alternative is `cvmfs_server list` that shows the status of all the repository.

Also, if you got multiple administrator, it might be useful to have a look into the gateways.

They help in speeding up the transaction and separate rights between different administrator.

You can setup gateways to allow access to only a subpath of the repo for instance.

Gateway are rather stables but not as battle tested as the classic setup.


I am leaving this opening somebody else wants to chin in, otherwise, I will close the issue in a couple of days.

Cheers,
Simone

**Comment by zbs** [comment]
Thanks for the help! I'll use `cvmfs_server list` for now. I'll look into gateways if the need arises.

**Comment by siscia** [comment]
Following the same logic, I close this issue.

**Comment by DrDaveD** [comment]
I have also often wished for this feature, and have responded to other people asking for it.  The problem with cvmfs_server list is that you can't select a specific repository.  Maybe the solution is to expand it to accept specific repositories, or a more user-friendly name would be cvmfs_server status.  I made a [JIRA ticket](https://sft.its.cern.ch/jira/browse/CVM-1925) with that suggestion.

**Comment by zbs** [comment]
The workaround I've been using is:
`cvmfs_server list | grep -E 'repository_name.*in transaction' 1>/dev/null && echo 'In transaction' || echo 'Not in transaction'`
You can turn it into a linux function and parameterize the repository_name.

**Comment by paulz1** [comment]
I think this feature could be still useful.
We use CVMFS in some CI system. We have a gateway and 2 publishers.
Actually, I have one publisher blocked and on the publisher I see (using `cvmfs_server list`) that a repository is in transaction.
But I'd like to have some more information ? Who open this transaction ? At which moment etc. ?
So cvmfs_server list doesn't give enough information for us.

**Comment by vvolkl** [comment]
Yes, I can see the usefulness of exposing this information. Some of it is already available in the gateway logs (`journatlctl -u cvmfs-gateway`) - at least the time when the last lease was given out.
