### ISSUE TITLE
cvmfs_preload from Stratum 1

### ISSUE THREAD

**Issue by ocaisa** [cvmfs/cvmfs#2618]
Following on from #2606 where we use a pre-populated cache for HPC MPI workloads, I'm concerned that this approach is not scalable at all since it will send all the load to Stratum-0 (so we can't really widely suggest it). In the docs it is very clear that this is the case, so I guess this is a feature request to ask if it could be possible to do an initial copy from Stratum-1 and only fall back to Stratum-0 for a final verification of whether the cache is up to date.

**Comment by jblomer** [comment]
With the `-u <url>` preload parameter, you can switch between stratum 0 and stratum 1 as necessary.  I'd not necessarily use the stratum 1 for the initial snapshot though because the replication thrashes the stratum 1 cache.  Instead, for preloading I'd recommend to establish a dedicated URL.  This URL can initially be simply an alias to the stratum 0.  As long as there are only a handful of preload destinations, that should work fine. If more sites preload, this URL can turn into a dedicated stratum 1 or a large cache in front of the stratum 0.

**Comment by jblomer** [comment]
Closing for the time being, please feel free to reopen if necessary.
