### ISSUE TITLE
EIO when entry changes file type

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2834]
Hi,

If an entry on a cvmfs file system changes file type (eg from a symlink to a directory), this can cause kernel to emit an EIO on a stat() / getattr() operation. This arises in 
 `fs/fuse/dir.c` at https://github.com/torvalds/linux/blob/bc491fb12513e79702c6f936c838f792b5389129/fs/fuse/dir.c#L1003 .
The cause of this is that CVMFS preserves inode numbers across a catalog reload, but doesn't account for the possibility of changing type. This means that the kernel can see an inode file type changing between successive lookup/getattr operations. This, apparently, breaks a fundamental assumption in the kernel https://www.spinics.net/lists/linux-fsdevel/msg190819.html  .
This can be mitigated by globally disabling kernel caching with `CVMFS_KCACHE_TIMEOUT=0` or by setting the specific inode's entry timeout to zero.

The `EIO` only happens once. That causes the kernel to invalide the inode, and a fuse `forget` is sent to CVMFS. This drops the cached inode entry and the next operation on the entry causes a new path->inode lookup resulting in a new inode number.

I'm not actually sure if there's a general solution to this that won't push a race elsewhere. Our specific scenario is the conversion of a symlink (that points to an off-cvmfs directory) into a directory of the same name.

Steps to repro:
1) Set up a repro publishing loop that changes an entry from a directory to a symlink on alternate publications. Make the repo TTL 1sec.
2) Mount the repo on a client and do a tight loop lstat()ing that entry, noting `errno`. - EIOs should quickly appear.

**Comment by jblomer** [comment]
Many thanks for the report and the detailed analysis!

That's an interesting problem.  In any case, it seems cvmfs needs to remember the type of the active inodes. That should be relatively easy to do.  The question is what to do with this information when a type conflict arises.  What we cannot do is invalidating the inode within a fuse callback because that can lead to a deadlock. So most likely, in such a case we'd need to issue a new inode for the entry.  The tricky bit is how this will be handled in the cvmfs inode tables. Because at this point, we'd have two inodes for the same path, which is currently not foreseen.

Let me think a little about it.

**Comment by jblomer** [comment]
Just for information, the corresponding [JIRA ticket](https://sft.its.cern.ch/jira/browse/CVM-2062)

**Comment by mharvey-jt** [comment]
Our mitigation for this is to set the kernel cache timeout for off-cvmfs symlinks to zero. 
https://github.com/cvmfs/cvmfs/pull/2950

**Comment by jblomer** [comment]
This issue is linked to the problem described in [CVM-2001](https://sft.its.cern.ch/jira/browse/CVM-2001). In both cases, it seems we need to break the current relationship between a path and exactly one live inode. Here's a sketch on how this may work

1. In the LOOKUP callback, there are two conditions where instead of the live inode we place the unique inode from the file catalogs in the inode tracker: when the file type changed and when we have an open file of that inode with a different content than its current version
2. We can use the most significant bits in the inode tracker to store the file type
3. The FORGET call need to take careful about the removal of path --> inode entries now that multiple inodes may point to the same path
4. For open, old inodes, we still need to be able to handle GETATTR queries, so we need to store the `struct stat` information of open files
5. When the file type changes, we may need to trigger an inode invalidatation (as usual, in a different thread) on the old one

This change requires a hard look an all the possible corner cases.

**Comment by jblomer** [comment]
Much simpler, turns out to be essentially a one-liner (modulo class rename and integration test): We need to track positive name lookups in the dentry tracker, which has been renamed because it is now not only tracking negative lookups anymore.  Tracking the positive name lookups results in eviction of the corresponding kernel-cached dentries during catalog reload.

So this issue _is_ quite different from CVM-2001. I'll create a separate PR addressing CVM-2001.

**Comment by jblomer** [comment]
> Much simpler, turns out to be essentially a one-liner (modulo class rename and integration test): We need to track positive name lookups in the dentry tracker, which has been renamed because it is now not only tracking negative lookups anymore. Tracking the positive name lookups results in eviction of the corresponding kernel-cached dentries during catalog reload.

Hm, it seems that this is too strong a measure. Test case 076 fails and there may be more problems because with this approach entries appear to be deleted after a catalog reload. So for the moment, we are only at a point where we detect changed file system types. More effort is needed on this issue.

**Comment by jblomer** [comment]
[Related discussion](https://patchwork.kernel.org/project/linux-fsdevel/patch/20210609181158.479781-1-amir73il@gmail.com/) found by @HereThereBeDragons

**Comment by jblomer** [comment]
For the record, CVM-2001 got fixed with #3043

**Comment by jblomer** [comment]
This should be fixed as a side effect of #2949, specifically of the new `fuse_expire_entry`

**Comment by jblomer** [comment]
We should adjust integration test 698 on platforms supporting `fuse_expire_entry`.

**Comment by HereThereBeDragons** [comment]
Yes PR #2949 should fix this issue.

Made a new issue #3172 for the integration test
