### ISSUE TITLE
Improve handling of noop transactions.

### ISSUE THREAD

**Issue by radupopescu** [cvmfs/cvmfs#2839]
Running `cvmfs_server publish` at the end of an empty transaction results in a new catalog and new revision for the repository, even though no data or metadata changes were introduced. In cases where the transaction/publish are run in a loop with high frequency, the extra space used in the repository and the amount of work for the garbage collector can grow considerably. With multiple publishers provisioned for a single repository using the gateway, this situation can be further exacerbated.

By default, if `cvmfs_server publish` detects that no changes have occured during the open transaction, a rollback should be performed. A new command-line flag for the publish command should activate the old behaviour (create a new catalog and revision even if noop).

**Comment by jblomer** [comment]
Reliably detecting that there are no changes is the uncomfortable bit. I think migrating `publish` to libcvmfs_server first will make this task easier.

**Comment by mharvey-jt** [comment]
(No opinion on this, where we are publishing continually, there are always changes and we usually have the reflog disabled entirely)

**Comment by bedroge** [comment]
We publish empty transactions after every use of `cvmfs_server ingest` to generate nested catalogs, because the `ingest` ignores the `cvmfsdirtab` file (that's still the case according to the docs?). I guess that would no longer work with this new approach? Is there a better way to work around this? The `-c` option is often not sufficient, as we usually have quite large tarballs that needs several nested catalogs.

**Comment by HereThereBeDragons** [comment]
As there is no strong oppinion for supporting this, we will close this for now.
