### ISSUE TITLE
Performance degradation at high core counts

### ISSUE THREAD

**Issue by jblomer** [cvmfs/cvmfs#2879]
As discussed with @elmsheus, ATLAS build machines using sources/dependencies from cvmfs see a performance degradation from around 32 cores to 64 cores.

@elmsheus @krasznaa If you could give us instructions on how to build Athena on a vanilla CentOS 7 node, we can try to reproduce the issue on our 64 core machine.

**Comment by elmsheus** [comment]
I hope the following works without permissions issues - others here should please correct me, if I've accidentally overlooked something.

First prepare the local build area and environment - if you build at CERN, then I assume you have access to afs and EOS, so I am skipping here some environment work-arounds that might be needed for a couple of packages in the later build if afs/EOS is not accessible - there might be a package build failure due to permissions problems, but that should not be a problem here to demonstrate the problem :
```
ssh somehost.cern.ch
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
setupATLAS
mkdir myathena
cd myathena
lsetup git
git clone https://:@gitlab.cern.ch:8443/atlas/athena.git
asetup none,gcc11,cmakesetup
```

Then first build the externals which takes 5-25 min depending on how much vCPUs are available on the machine - this step usually works fine without too much CVMFS load:
```
./athena/Projects/Athena/build_externals.sh -c -t Release >& external.log &
```
This configuration uses `Release` instead of `RelWithDebInfo`.

Subsequently build athena - this takes 1-5h depending on the number of vCPUs - here the CVMFS process load is usually quickly visible on machines with 64 or 128 vCPUs:   
```
./athena/Projects/Athena/build.sh -acmi  -t Release  > build.log 2>&1 &
```
Overall the CPU utilisation is then only ~60-70%. 

One note: if we move gcc or clang out of CVMFS, ie. do not use gcc/ld from /cvmfs/sft.cern.ch/lcg/releases/gcc/11.2.0-8a51a/x86_64-centos7/bin/gcc etc. but install it locally the CPU utilisation recovers by 10-20% - in my tests on Google/AWS not all was recovered, but it seems to work better for Attila on a local desktop build machine.

Pinging also @EdwardMoyse

**Comment by krasznaa** [comment]
Let me add 1-2 more things. :wink:

In order to build Athena at all, you need:
  - Access to `/cvmfs/atlas.cern.ch`, `/cvmfs/atlas-condb.cern.ch` and `/cvmfs/sft.cern.ch` as a minimum;
  - A CentOS 7 OS with the [HEP_OSlibs](https://gitlab.cern.ch/linuxsupport/rpms/HEP_OSlibs/-/tree/el7) meta-package installed.

For a "proper build" you would also need access to EOS, and you'd need to perform the build as a user belonging to the ATLAS (ZP) group. But the things left out of the build without those two are not relevant for this issue luckily.

If you don't have CC7 set up "just so" on your test machine, you can just use a Singularity image that we provide through CVMFS. With the `setupATLAS` alias that Johannes described above, you can start such a container with:

```
setupATLAS -c centos7
```

In general, this can provide you with a decent OS for the Athena build on any linux box that has CVMFS set up natively on it.

A couple more things:
  - You can get our repository without any authentication as well, simply with `git clone https://gitlab.cern.ch/atlas/athena.git`;
  - The build scripts that Johannes described will create a `build/` directory just beside the `athena/` directory. So be sure that you would have enough space on the disk where you cloned the repo to. (O(100 GB) for a "Release" build.)
  - The Athena build can be exercised even a bit better if you use Ninja for the build. By default the `build.sh` script will use CMake's default "GNU Makefiles" generator. You can override that (in the environment set up by the `asetup` call listed in Johannes's description) like:

```
export PATH=/cvmfs/sft.cern.ch/lcg/contrib/ninja/1.10.0/Linux-x86_64:${PATH}
./athena/Projects/Athena/build.sh -acm -t Release -x -GNinja
```

Note that you can skip the `-i` argument from `build.sh`'s command line. As you don't need to install the built project when the build is done.

**Comment by jblomer** [comment]
Many thanks for the instructions!  I did manage to build the externals on an EL7 box.  I then logged in again, ran `setupATLAS` and `lsetup git` again and tried the Athena build, but there I get 

```
$ ./athena/Projects/Athena/build.sh -acm -t Release 
Set LCG_RELEASE_BASE = /cvmfs/sft.cern.ch/lcg/releases
Set TDAQ_RELEASE_BASE = /cvmfs/atlas.cern.ch/repo/sw/tdaq
Setting up AthenaExternals from: /home/jblomer/myathena/build/install/AthenaExternals/22.0.61/InstallArea
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
CMake Error: CTEST_USE_LAUNCHERS is enabled, but the RULE_LAUNCH_COMPILE global property is not defined.
Did you forget to include(CTest) in the toplevel CMakeLists.txt ?
Generate graphviz: /home/jblomer/myathena/build/build/Athena/packages.dot
Reading GraphViz options file: /home/jblomer/myathena/athena/Projects/Athena/CMakeGraphVizOptions.cmake
Writing /home/jblomer/myathena/build/build/Athena/packages.dot...
TIMESTAMP::PROJECT_CONFIG:: 0 ::
```

Do the externals and the Athena build need to happen from the same session?

**Comment by EdwardMoyse** [comment]
Hi Jakob,

I think if you look at the instructions here you might get some help:
https://atlassoftwaredocs.web.cern.ch/guides/build_release/#building-athena-alone

Specifically you need to get the right CMake version:

asetup none,gcc11,cmakesetup

And then I *think* you need to add the externals to the path:

source ./install/AthenaExternals/22.0.1/InstallArea/x86_64-centos7-gcc11-opt/setup.sh

(I can't remember whether this is also called inside Athena/build.sh, but I
think it can't hurt to do it twice)

Cheers,

Ed

**Comment by elmsheus** [comment]
If you start from scratch again in a new session before the athena build step, you need again `asetup none,gcc11,cmakesetup`. It does not have to be the same session but you need the same environment:
```
ssh somehost.cern.ch
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
setupATLAS
cd myathena
lsetup git
asetup none,gcc11,cmakesetup
```
Hope that helps,
Cheers, Johannes

**Comment by krasznaa** [comment]
As it was pointed out, you missed executing the `asetup` command.

The reason I'm commenting as well is just to say that you shouldn't start bothering the `build_env.sh` script. :stuck_out_tongue: That's something that comes in handy when you want to set up an environment in which you could cmake-configure and build the Athena project "by hand". So we tend to use that `build_env.sh` script a lot when developing the main project's CMake configuration.

But `build.sh` **is** in fact making use of `build_env.sh` behind the scenes. In order to just build our projects, you only need to use the `build_externals.sh` and `build.sh` scripts. Everything else is only needed when you want to do something more complicated/fancy.

Cheers,
        Attila

**Comment by jblomer** [comment]
Many thanks, of course, forgotten `asetup`.

I can now build Athena on our 16 core test node.  As expected, this shows essentially full utilization of the node.  Next step, I'll grab a free slot on our 64 core node and retry. This may take a few days depending on the other benchmarks on that node.

**Comment by jblomer** [comment]
What I see on our 64 core node (EPYC 7702P, 128 hyperthreads) looks pretty reasonable:

- Cvmfs cache filled with ~7.5GB of data
- Among the cvmfs processes, the main load is on the one serving sft.cern.ch, typically 100%-200%, sometimes up to 300% for short periods
- Machine load: stable at ~145
- In the cvmfs internal counters (`cvmfs_talk -i sft.cern.ch internal affairs`) I don't see any indication of cache thrashing

I enabled `CVMFS_INSTRUMENT_FUSE=yes` in /etc/cvmfs/default.local so that the latency histograms in the `internal affairs` get filled. On our machine they look normal, most calls around 4-8us. Perhaps you could enable them on your machine, too, and attach the output.

Two settings that *may* help (although, no indication that they do from my box):
```
CVMFS_KCACHE_TIMEOUT=300 # increases kernel cache timeout from 1 minute to 5 minutes, i.e. more kernel cache hit
CVMFS_MEMCACHE_SIZE=128 # increase the cvmfs meta-data cache from 16M to 128M (although no thrashing seen on my box)
```

Our box has an EL8, I build in the EL7 singularity container.  Perhaps that explains the difference to a native EL7?

**Comment by jblomer** [comment]
This is cvmfs 2.9.0 using libfuse2, btw. In order to use fuse3, just install the `cvmfs-fuse3` package and remount the repositories. Changing between fuse2 and fuse3 may make a difference, too.

**Comment by krasznaa** [comment]
I'm afraid that just looking at machine load is not the right metric here. :frowning: What I actually saw in my 64-thread tests was that the load was higher in the cases when my CPU efficiency was lower.

While my CPU has all of its cores loaded "nicely", the overall load should roughtly equal the total number of threads of the machine. Seeing a load of 145 for a 128-thread node is already suspicious on this account.

Could you monitor your CPU usage during the build? With just something as simple as `top` / `htop` for instance. I would really be interested in what you see for the CPU usage there. Since in my tests I could never get CPU efficiency/usage above 70-80% with 64-threads while taking the compiler from CVMFS. (Whatever the load value may have been at the same time.)

**Comment by elmsheus** [comment]
I am attaching here the plots for overall CPU usage, throughput and IOPS from the GCS node monitoring: ![image](https://user-images.githubusercontent.com/8158216/161960555-caf45d48-0898-4788-8d8f-7a5b9017eae5.png)

This supports what Attila said in the comment before. I don't have plots at the moment from a 16 or 32 CPU node but the CPU usage looks better there.

**Comment by jblomer** [comment]
All right, I see the difference in CPU utilization between the 16 core node (~90%) and the 64 core node (50-70%).  I'll look further into it.

Do you have instructions at hand on how to pick a local compiler instead of the one from cvmfs?

**Comment by elmsheus** [comment]
There are 2 ways to relocate the gcc/binutils/cmake:
(1) Use the docker container that Attila has build
(2) Copy gcc, binutils from the SFT CVMFS area and cmake from the AtlasLocalRootBase CVMFS to a local disk

For (1) use e.g. singularity via AtlasLocalRootBase (it's all wrapped in setupATLAS):
```
setupATLAS -c docker://atlas/centos7-atlasos-dev:latest-gcc11
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
alias setupATLAS='source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh'
setupATLAS -c docker://atlas/centos7-atlasos-dev:latest-gcc11
setupATLAS -q
asetup none,gcc11,cmakesetup --gcclocation=/opt/lcg/gcc/11.2.0/ --cmakearea=/opt/cmake/ --cmakeversion=3.21.3
cd /srv/
mkdir myathena
cd myathena
lsetup git
git clone https://:@gitlab.cern.ch:8443/atlas/athena.git
...
```

For (2) that's more manual work - assume your local disk is /scratch
gcc:
```
cd /scratch
mkdir lcg
cd lcg
mkdir gcc
cd gcc
cp -r -p /cvmfs/sft.cern.ch/lcg/releases/gcc/11.2.0-ad950 .
mkdir 11.2.0
cd 11.2.0
ln -s /scratch/lcg/gcc/11.2.0-ad950/x86_64-centos7 x86_64-centos7
```
Then change `/scratch/lcg/gcc/11.2.0/x86_64-centos7/setup.sh` the first line:
```
source /scratch/lcg/binutils/2.37-4177a/x86_64-centos7/setup.sh
```

binutils:
```
cd /scratch
mkdir binutils
cd binutils
cp -r -p /cvmfs/sft.cern.ch/lcg/releases/binutils/2.37-355ed .
mkdir 2.37
cd 2.37
ln -s /scratch/lcg/binutils/2.37-355ed/x86_64-centos7 x86_64-centos7
```
Then change in `/scratch/lcg/binutils/2.37/x86_64-centos7/setup.sh` the first line:
```
BASE=/scratch/lcg/binutils/2.37-355ed/x86_64-centos7
```

cmake:
```
cd /scratch
mkdir cmake
cd cmake
cp -r -p /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Cmake/3.21.3 .
```

Then use the relocated local gcc/binutils/cmake with:
```
asetup none,gcc11,cmakesetup --gcclocation=/scratch/gcc/11.2.0/ --cmakearea=/scratch/cmake/ --cmakeversion=3.21.3
```

I hope I did not introduce any bugs, while coping them from my notes.
Cheers, Johannes

**Comment by jblomer** [comment]
Many thanks for the instructions!

I think I see the problem, it has to do with the management of kernel page caches by cvmfs. That is currently a conservative approach that directs more calls than necessary up to the fuse module. Using the kernel caches more aggressively requires additional logic to make sure correct data are delivered when files change.

I tried with a quick & dirty patch (that would lead to errors down the road) with which I get almost full utilization on the 64 core node.

We'd need to think a little about how to address this properly. Many thanks for walking me through this use case!

I'll keep you posted on the progress in this ticket.

**Comment by jblomer** [comment]
There is a nightly build with the patch applied available here:
http://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-3340/

@elmsheus @krasznaa This should improve the node utilization

**Comment by elmsheus** [comment]
@jblomer, thanks for this update. I've setup/updated 2 Google cloud nodes and did some quick builds:

112 vCPU AMD EPYC 7B13 node
* Athena,master,gcc11,RelWithDebugInfo,make:
  - AthenaExternals 4.9min (before 8.7min)   
  - Athena 95.8 min (before 112min)
* Athena,master,clang14,Release,Ninja
  - AthenaExternal 3.7 min (before 8.6min)
  - Athena 68.8min and 91.5min (before 61.5min) - not sure what is happening here...

60 vCPU Intel (Cascade Lake) node
* Athena,master,gcc11,RelWithDebugInfo:
  -  AthenaExternals 8.3min (before 12.3min)   
  -  Athena 104.0 min (before 124min)

So, I see a 10-15% build time improvement for the Athena part.

The 60 vCPU Intel node shows now ~85-90% CPU utilisation in the monitoring.

 I am not fully sure what is happening on the 112 vCPU AMD node - the CPUs are slightly better utilised but still only 50-60% but there are still quite some fluctuations over time in the monitoring visible - there is something weird with the Ninja/clang14 build in addition. I might be hitting some other bottlenecks.

**Comment by elmsheus** [comment]
I've installed a brand new 112 vCPU AMD node from scratch only with 2.10-nightly CVMFS release - it seems there had been problems with the other 112 vCPU AMD node yesterday...

Here are 2 new measurements:
* Athena,master,clang14,Release,Ninja
  - AthenaExternal 3.8 min (before 8.6min)
  - Athena 44.3 min  (before 61.5min) 
* Athena,master,gcc11,RelWithDebugInfo,make:
  - AthenaExternals 4.3min (before 8.7min)   
  - Athena 76 min (before 112min)

So the Athena build part is about 30% faster. The CPUs utilisation on the node is now fluctuating on average in the range of 60 to 90%. I still see some high CMFS process load from time to time, but without any prove we might be hitting now parallelisation bottlenecks of the build.

@jblomer, when do you think this CVMFS version could be rolled out into production ?

**Comment by jblomer** [comment]
Many thanks for the numbers!

I think it would be very useful to get some experience from heavily used nodes. For production nodes, however, we should merge the PR first and then let the full integration test suite run on it. We currently have some issues with the CI nodes, I'll let you know when we have a well tested nightly.

One thing to keep in mind is that we won't test hotpatching from a nightly build to a release build, so once 2.10 proper is released, you'd need to unmount and remount on the nodes that run a nightly.

**Comment by jblomer** [comment]
We have a build the ran through our integration tests here: https://ecsft.cern.ch/dist/cvmfs/nightlies/cvmfs-git-3345/

Please let us know if you see any issues with this build. Please also keep in mind that once you'll upgrade to the proper cvmfs-2.10 release RPM, you'll most likely need to unmount and remount cvmfs repositories on the nodes that have the nightly build.

**Comment by elmsheus** [comment]
I've installed  cvmfs-2.10.0-0.3345.89a8862a4df2c448git.el7.x86_64.rpm on a 192 vCPU AWS node and rebooted the node. I observe the same (fast) build time for a clang14,Release,Ninja build as with the previously tested RPM cvmfs-2.10.0-0.3340.89a8862a4df2c448git.el7.x86_64.rpm
