### ISSUE TITLE
enable fuse caching of symlinks, if supported by kernel and libfuse

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2949]
Improve performance in symlink-heavy repos by allowing the kernel to cache symlink dereferences.

Requires rhel8 + fuse 3.10.

This has the potential to cause an issue over catalog update if the symlink changes  - the kernel will return the old value until the cache expires.

**Comment by mharvey-jt** [comment]
reference implementation in PR #2959

**Comment by jblomer** [comment]
That would be a very welcome performance improvement but unfortunately the fact that we can return stale symlinks from the page cache is a major issue. I think it's also an issue that we are likely to hit in practice. For instance, repository maintainers often use a `latest` symlink that points to the most recent software version.

We should first see if active cache invalidation during catalog updates can work race-free. If so, there are a few options I can think of:

1. Track all symlinks given to the kernel and invalidate them all on catalog updates
2. Invalidate only changed symlinks, which means we would need to track the symlinks themselves or their hash or last-updated timestamp

**Comment by mharvey-jt** [comment]
One thing to note: When kernel fuse's symlink caching is enabled, the behaviour of symlink resolution changes:
* without caching, the i_size attribute of the inode is effectively ignored - the length of the symlink value returned by cvmfs in the FUSE_READLINK reply is used
* with caching, the symlink value is truncated at the i_size of the inode. 
This means there's a toctou race between a cvmfs update that changes a symlink's value and FUSE's two-phase. LOOKUP, READLINK. This means that symlink that changes value to a longer string can end up with a value incorrectly truncated at the previous value's length

**Comment by jblomer** [comment]
I was afraid that may happen. Probably the same underlying issue than with #2834: stale data in the dentry cache. A possibly workaround (for both issues) should be disabling active cache eviction (set `FuseInvalidator::g_fuse_notify_invalidation_ = false`). In this case, new catalogs cause the cache to drainout according to `CVMFS_KCACHE_TIMEOUT`. Clients then take an additional minute (by default) to apply updates, during which all new lookups get a zero-timeout.

Ideally, we'd be able to set the timeout of kernel cache dentries to zero, rather than invalidating them which causes new inodes to be issued for a certain path.

**Comment by jblomer** [comment]
With a small fix to fuse+libfuse, we are in a much more comfortable situation (to be tested):
https://sourceforge.net/p/fuse/mailman/message/37703271/

**Comment by HereThereBeDragons** [comment]
[New function: fuse_lowlevel_notify_expire_entry · Issue #707 · libfuse/libfuse](https://github.com/libfuse/libfuse/issues/707) and [kernel patch](https://git.kernel.org/pub/scm/linux/kernel/git/mszeredi/fuse.git/commit/?h=for-next&id=53e949edb7692dce02220eba926c9d75ecbb47f7)
