### ISSUE TITLE
Support for musl libc

### ISSUE THREAD

**Issue by amadio** [cvmfs/cvmfs#3070]
Some Linux distributions, like Alpine Linux, for example, build on top of [musl libc](https://musl.libc.org/) instead of glibc. Using musl is also possible in Gentoo Linux, but it's optional. We have a tinderbox testing packages against musl, and that tinderbox filed a [bug](https://bugs.gentoo.org/832422) for CVMFS on Gentoo as it doesn't seem to be ready to be compiled with musl libc. The installation fails at configuration time, complaining about lack of the `execinfo.h` header, which is not provided by musl. Please see the full details in the bug report.

**Comment by jblomer** [comment]
Many thanks for the report!  We are using `backtrace()` and `backtrace_symbols()` from the GNU extensions, so I'm afraid that not having those is currently unsupported.

The use of backtrace is rather limited.  If this is the only issue with musl, we would merge a patch that drops stacktrace generation on such platforms. If it turns out, however, that musl libc requires significantly more code changes or conditional code blocks, we would need to reconsider if it's worth the maintenance effort.

**Comment by jblomer** [comment]
Closing for the time being. Please feel free to reopen if necessary.
