### ISSUE TITLE
cvmfs packaging on Debian community(not by cernvm)

### ISSUE THREAD

**Issue by OriPoin** [cvmfs/cvmfs#3091]
I am working on packaging cvmfs into Debian, here is the [repo](https://salsa.debian.org/hpc-team/cvmfs/) of hpc team. 
Related merge request url is [https://salsa.debian.org/hpc-team/cvmfs/-/merge_requests/1](https://salsa.debian.org/hpc-team/cvmfs/-/merge_requests/1).

I think it would be more convenient to get cvmfs directly from Debian repo. And with the help of Debian QA (quality assurance), we can make cvmfs better quality.

The difference between cvmfs packaged by us and cern, also the issue I want to discuss are:

1. Only support fuse3, drop fuse2 libs. I know there are probably a lot of older systems running cvmfs, is it possible to drop old fuse2 support?
2. Disable debug option of client and server for now, drop *_debug libs. Since dpkg and rpm all can strip debug symbols from compiled products, and loglevel parameter can easily control log with or with not debug info. Wouldn't it be a better choice to leave this to the package manager?
3. Manages, mostly generated by help2man. 

>>If no manual page is available, this is considered as a bug and should be reported to the Debian Bug Tracking System (the maintainer of the package is allowed to write this bug report themselves, if they so desire). Do not close the bug report until a proper man page is available.

From [Debian policy](https://www.debian.org/doc/debian-policy/ch-docs.html#manual-pages), as a large set of commond line tools, cvmfs should have **proper man pages**. I generated some pages using help2man, and want to refine them with the help of the developers and submitted to here.

And there are also some misc differences, which you can see in the link above.

**Comment by jblomer** [comment]
Many thanks for this effort!

Let me say that our primary objective is to provide well-tested packages with well-controlled dependencies to reduce variation across all the supported platforms and to facilitate debugging. We will prioritize aspects that we think are relevant for stability and debugging over package policies.

That said, within these constraints we are happy to merge PRs with improvements to the packaging!  Concretely, regarding the three points:

1. I think it makes sense to change the cmake build system so that it looks for both fuse2 and fuse3 and accepts if either of them is present. Such a change could be merged right away.  As for dropping fuse2, I don't think that's trivial. One of the issues is upgrading (thus hotpatching) existing systems which are mounted with fuse2 libraries (even though fuse3 libs may exist). What I could imagine for the packaging is cvmfs-fuse2 and cvmfs-fuse3 packages where one only needs to have one or the other. That still will cause some problems (new sub packages typically do) but what would be nice about it that users are more likely to pick fuse3 libraries than with the current approach (optional cvmfs-fuse3 package).
2. The debug libraries are often necessary to investigate issues on production systems.  They have more log messages built-in (as in compiled in) and they are compiled with `-O0` so that stacktraces giver proper information. So I would not want to drop them from the package.
3. That sounds very useful. We had a long time ago a stuck attempt to add man pages. Our main concern back at the time was to ensure that there is only a single source of information. This seems to be the case with the use of `help2man`.

**Comment by jblomer** [comment]
Closing for now, please reopen if you are still working on that topic.
