### ISSUE TITLE
RFE: high precision mtime

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3413]
Hi,

Currently CVMFS stores the mtime of a file within the catalog as an INTEGER, which is 32b. This isn't sufficient precision to store the exact timestamp of a source file, which we would like to use for comparing files. Could the mtime in the catalog be extended to 64bit in. backwards compatible way?

**Comment by jblomer** [comment]
That should be possible. The problem is not the column type, sqlite `INTEGER` is 64 bit. But the `mtime` column does store seconds since UNIX epoch, so we cannot change the precision of that column in a backwards compatible way. But we can add a new column with the nanosecond part, which would be ignored by old clients.

We may want to make high-precision timestamps optional during publishing, so that when it's not needed, the nanosecond column would contain zeros and compress nicely.

**Comment by mharvey-jt** [comment]
subsecond timestamps requires FUSE to support  `statx()` - patches for that have just landed in 6.6 https://lore.kernel.org/lkml/ZPYxd0g9S4og17QN@maszat.piliscsaba.szeredi.hu/ . Once supported in libfuse, it should be possible to add support to cvmfs. 
I think it can probably work without any schema changes - realistic second and nanosecond resolution timestamps have very different ranges, so the type can be determined dynamically - although that comes at the cost of breaking compatibility with older clients
