### ISSUE TITLE
failover if Stratum-1 is behind the Stratum-0

### ISSUE THREAD

**Issue by jose-caballero** [cvmfs/cvmfs#3637]
Hi, 

I am going to assume the client knows when the contact again the Stratum-1 to update content by comparing the revision numbers. That would also prevent the client from getting data from the Stratum-1 in the middle of a snapshot. 

If that is not the case, then this Issue may not make any sense at all. Ignore this in that case :) 
But, if this is the mechanism in place, or similar...

We still have the problem that the client doesn't know if the Stratum-1 is stuck in the past, and behind the Stratum-0, right? 
Would it be possible to add the URL for the Stratum-0 to the .cvmfspublished file on the Stratum-1, and make the client to use it to also check the revision number upstream and failover if they don't match? 

Food for thought.

Cheers,
Jose

**Comment by DrDaveD** [comment]
Sorry, that won't work, for multiple reasons.

First, it's impossible to know how long it should take for a revision to arrive on a stratum 1.  In the early days we tried to monitor stratum 1s by comparing stratum 0 revision numbers and there were huge numbers of false alarms.  Revisions on stratum 0s increase at unpredictable rates, and they are of unpredictable size and therefore transfer time.  This is why the monitor now only checks stratum 1s for the number of hours since their last successful snapshot.

Second, the list of stratum 1s can be long, and there's no way for clients to figure out when it makes sense to stop trying them to find a newer revision.  Some of the stratum 1s will be on the other side of the world.

Third, stratum zeros are generally engineered to serve only a limited number of stratum 1s, not the whole world the way stratum 1s are.  Some stratum zeros protect the IP address ranges that they serve so only stratum 1s can contact them.

There's probably more reasons but those are the ones I can think of now.
