### ISSUE TITLE
Pop!_OS 22.04 compatibility

### ISSUE THREAD

**Issue by Juanki0396** [cvmfs/cvmfs#3643]
I am trying to work from my personal laptop as a summer student but cvmfs says that my distribution is not compatible. Since Pop!_OS is based on Ubuntu, it should not be any problem at using it. My current version is Pop!_OS 22.04 LTS and it has the core features of Ubuntu 22.04.

**Comment by vvolkl** [comment]
Hi @Juanki0396! I quickly tried with a Pop OS docker image based on focal and our packages installed fine. Please provide some more details: how exactly did you install cvmfs, and what was the error message (please copy-paste)?

**Comment by Juanki0396** [comment]
I have follow the guidelines from your [tutorial](https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html). 
My default local looks like this:
```
CVMFS_REPOSITORIES=sw-nightlies.hsf.org,sw.hsf.org,grid.cern.ch
CVMFS_CLIENT_PROFILE=single
CVMFS_HTTP_PROXY=DIRECT
``` 
I have run `cvmfs_config probe` and everything looks right:
```
Probing /cvmfs/sw-nightlies.hsf.org... OK
Probing /cvmfs/sw.hsf.org... OK
Probing /cvmfs/grid.cern.ch... OK
```
But if i try to source the key4hep stack using `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh`, i get this:
```
Unsupported OS or OS couldn't be correctly detected, aborting...
Supported OSes are: CentOS/RHEL 7, AlmaLinux/RockyLinux/RHEL 9, Ubuntu 22.04
```

**Comment by Juanki0396** [comment]
Oh, maybe the problem is from key4hep stack.

**Comment by vvolkl** [comment]
Yes indeed, CVMFS looks to be fine, and this is an issue with the key4hep stack installed on it. I think a workaround maybe to source the full path of the setup script, like `/cvmfs/sw.hsf.org/key4hep/releases/latest/x86_64-ubuntu22.04-gcc11.4.0-opt/key4hep-stack/2024-04-12-gvsdn4/setup.sh` instead of the short path,  as the detection is not working. You can open an issue in https://github.com/key4hep/key4hep-spack/issues .
