### ISSUE TITLE
Proxy changed without reason to DIRECT

### ISSUE THREAD

**Issue by adriansev** [cvmfs/cvmfs#3648]
Hi! so with a configuration that have
```
CVMFS_HTTP_PROXY='http://FQDN1:3128;http://FQDN2:3128;http://FQDN3:3128'
```
with working squids seen in `wlcg-squid-monitor`, i get these messages:

```
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from (none) to http://IP1:3128. Reason: set random start proxy from the first proxy group
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from (none) to http://IP1:3128. Reason: cloned
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from http://IP1:3128 to DIRECT. Reason: set random start proxy from the first proxy group
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) CernVM-FS: linking /cvmfs/alice.cern.ch to repository alice.cern.ch
```

which i really do not want .. any idea about this problem?
Thanks a lot!

L.E. Alma9/cvmfs-2.11.3-1.el9.x86_64

**Comment by HereThereBeDragons** [comment]
hi
are you sure that 
```
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from (none) to http://IP1:3128. Reason: cloned
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from http://IP1:3128 to DIRECT. Reason: set random start proxy from the first proxy group
```

was indeed for the `default` manager? it says it is cloned. so it should be the `external` download manager. and then switching to `DIRECT` would be correct.

also i guess your IP replacements are all pointing to working IPs

**Comment by adriansev** [comment]
Hi @HereThereBeDragons ! I do not know what means "manager" .. this is the cvmfs installed on a worker node, with the CVMFS_HTTP_PROXY pointing to the local squids.
My expectation is that only if the squid from list do not work then go to DIRECT... and yes, the ip replacement is pointing to working IPs (tested for connection with nc)
I can provide more detailed and unedited logs through email (my email is Adrian dot Sevcenco at cern)

**Comment by DrDaveD** [comment]
The "manager" is the cache manager.  alice.cern.ch does not have any `external` links so I would think the external cache manager would not be relevant here.  On the grids only `osgstorage.org` and `storage.igwn.org` repositories use both `default` and `external` cache managers.

Adrian, please attach here the output of these commands (while alice.cern.ch is mounted):
```
sudo cvmfs_talk -i alice.cern.ch parameters
sudo cvmfs_talk -i alice.cern.ch proxy info
```

**Comment by HereThereBeDragons** [comment]
even if the external downloadmanager is not being used, it is created during mounting by cloning from the normal downloadmanager and the proxy should switch to `DIRECT` because nothing is set.

**Comment by HereThereBeDragons** [comment]
hello
having a look at the logs and the different branches i am positive that there is an issue with the log output but not with the logic. the output below is definitely refering to the external downloadmanager even though it says `default`

```
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from (none) to http://IP1:3128. Reason: cloned
Aug  5 22:04:41 a01 cvmfs2[3868]: (alice.cern.ch) (manager 'default') switching proxy from http://IP1:3128 to DIRECT. Reason: set random start proxy from the first proxy group
```

i think during packporting some PRs for better logging to 2.11.3 [1] from our devel branch [2], there was some small portion being missed out. this does not affect any logic. it is just that during the creation of the external download manager (which is created via `Clone()` from the normal download manager) its name is not properly propagated to the external download manager - so it still replies in log messages as `default` even though it is `external`. 

This issue still exists in 2.11.4 but will be fixed in 2.12


[1] 2.11.3
https://github.com/cvmfs/cvmfs/blob/168de835e2c6dbafe750878c02291bba84610a95/cvmfs/network/download.cc#L2969-L2973
[2] devel
https://github.com/cvmfs/cvmfs/blob/885557c62ab41b655752ff2e0f9d032f346ab2d2/cvmfs/network/download.cc#L2997-L3001

**Comment by adriansev** [comment]
@HereThereBeDragons sorry, just to be certain: so the logging is wrong, and actually the proxy is not `direct` but the first proxy specified in the list of proxies, right?
And additionally, the specific order of proxies to be tried out is guaranteed ?
Thanks a lot!

L.E. And if i want to disable fallback to `direct` should i just set `CVMFS_FALLBACK_PROXY=""` ? i would prefer to have jobs failures if my 3 squids are somehow down...

**Comment by HereThereBeDragons** [comment]
@adriansev 
1. the logging is wrong. it refers to a different downloadmanager (for external data) which is being set to `DIRECT`. you are not using it but it is created for each mount point anyway. so the line with `cloned` and the line afterwards you can ignore. 

2. it depends if you have it in a single proxy group or multiple proxy groups. as far as i know within a proxy group the selection of a proxy is random (until all were tried). between proxy groups selection is done via round-robin

3. yes that should work. but you need to explicitly list your proxies. otherwise `DIRECT` will be used

**Comment by HereThereBeDragons** [comment]
some more info can be found here: https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#proxy-lists
