### ISSUE TITLE
repo becomes unreadable (permission 700) after abort

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/cvmfs#3658]
Migrating https://its.cern.ch/jira/browse/CVM-2071  to github issue.

Issue is described here: https://cernvm-forum.cern.ch/t/repo-permissions-changing-after-abort/163

It happens on both publishers and stratum 0/gateway.

Reproduced with cvmfs-server-2.11.3 again.

**Comment by rptaylor** [comment]
The normal permissions can be restored by doing an empty publish operation, but this can be a bit alarming to publish a repository in a state that by all appearances would be unreadable to all users.

**Comment by vvolkl** [comment]
Ryan, thanks for resurfacing this!

This issue is less mysterious as it first appeared to me. `/cvmfs/repo.dev.computecanada.ca` is an overlay mount, and the permissions come from the scratch directory used to record changes in the rw mode, not the actual repository catalogs. This scratch directory gets (re-)initialised with the wrong directory also on abort, but the publication command uses the right ones to recreate it after having wiped it.

I've added a fix to intitialise the scratch dir consistently.
